email: your-email@domain.com
description: Docmentazione tecnica per l'implementazione di ANPR
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll
lang: it

# Build settings
markdown: kramdown
gems:
  - jekyll-feed
  - jekyll-seo-tag
exclude:
  - Gemfile
  - Gemfile.lock

# Custom vars
theme_color: "#0066cc"
css_theme: t-Pac
owner: Ministero degli interni
logo: http://designer.italia.it/images/loghi/logo-it.svg

collections:
   pages:
     output: true
     permalink: /:path/
     layout: page

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "pages"
    values:
      subnav: "subnav"
